security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        loginProvider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy

            form_login:
                login_path: login
                check_path: login
                provider: loginProvider
            
            logout:
                path: /logout
                target: /
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, roles: [IS_AUTHENTICATED_FULLY,ROLE_USER] }
